packages:
  - "apps/web"
  - "apps/desktop"
  - "server"
  - "shared"
overrides:
  qs@>=6.11.1 <6.15.2: ">=6.15.2"
  ws@>=8.0.0 <8.20.1: ">=8.20.1"

allowBuild:
  - esbuild
allowBuilds:
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  tesseract.js: true
